version: 2.1
executors:
  deploy_container:
    docker:
      - image: circleci/python:3.8.7
    working_directory: ~/work

orbs:
  aws-cli: circleci/aws-cli@2.0.3

commands:
  install_dependency:
    steps:
      - run:
          name: pip insall
          command: |
            mkdir packages
            pip install -r requirements.txt -t ./packages
  lint_and_test:
    steps:
      - run:
          name: lint and test
          command: echo "any lint and test here"
  create_artifact:
    steps:
      - run:
          name: create zip file
          command: |
            cd packages
            zip -r ../deploy-files.zip .
            cd ../
            zip deploy-files.zip lambda_function.py
  deploy:
    steps:
      - run:
          name: deploy
          command: |
            aws --version
            aws lambda update-function-code --function-name circleci-trial-func --zip-file fileb://deploy-files.zip

jobs:
  lint_and_test:
    executor: deploy_container
    steps:
      - checkout
      - install_dependency
      - lint_and_test
  
  deploy:
    executor: deploy_container
    steps:
      - checkout
      - aws-cli/install
      - install_dependency
      - create_artifact
      - deploy

workflows:
  version: 2
  first-workflow:
    jobs:
      - lint_and_test:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - lint_and_test